### ISSUE TITLE
Cannot implement a method that returns "ao" (array of object paths)

### ISSUE THREAD

**Issue by acheronfail** [dbus2/zbus#349] opened 2023-05-18 02:08 UTC
First of all - awesome library, it's fantastic!

I'm trying to query the system bus and call NetworkManager's `GetAllDevices` method. This is my current attempt:

```rust
use std::error::Error;

use futures_util::StreamExt;
use zbus::{dbus_proxy, zvariant::Value, Connection};

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager/Devices",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager",
    gen_blocking = false
)]
trait Devices {}

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager",
    gen_blocking = false
)]
trait NetworkManager {
    #[dbus_proxy(signal)]
    fn state_changed(&self) -> zbus::Result<()>;

    #[dbus_proxy(object = "Devices", name = "GetAllDevices")]
    fn get_all_devices(&self) -> zbus::Result<Array<OwnedObjectPath>>;
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {
    let connection = Connection::system().await?;
    let proxy = NetworkManagerProxy::new(&connection).await?;
    println!("nm: {:?}", proxy.get_all_devices().await);

    let mut stream = proxy.receive_state_changed().await?;
    while let Some(change) = stream.next().await {
        println!("nm state change: {:?}", change);
    }

    Ok(())
}
```

But it's returning with 

```txt
Err(Variant(SignatureMismatch(Signature("ao"), "`o`")))
```

I've tried various combinations of `Vec<String>`, `Array<String>`, `Array<ObjectPath>`, etc. And nothing seems to change the error message.

How can I instruct the `dbus_proxy` macro to generate the right signature to get this working?

**Comment by acheronfail** [comment] 2023-05-18 02:55
I managed to get it slightly working with this:

```rust
#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager",
    gen_blocking = false
)]
trait NetworkManager {
    #[dbus_proxy(signal)]
    fn state_changed(&self) -> zbus::Result<()>;

    #[dbus_proxy(name = "GetAllDevices")]
    fn get_all_devices(&self) -> zbus::fdo::Result<Vec<OwnedObjectPath>>;
}
```

But it's not using the `object` attribute, so I wonder how I'm meant to set that all up?

**Comment by acheronfail** [comment] 2023-05-18 03:42
So, I've got something working:

```rust
use std::{collections::HashMap, error::Error};

use zbus::{
    dbus_proxy,
    zvariant::{ObjectPath, OwnedObjectPath, Value},
    Connection,
};

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager/IP4Config",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.IP4Config",
    gen_blocking = false
)]
trait NetworkManagerIP4Config {
    #[dbus_proxy(property)]
    fn address_data(&self) -> zbus::Result<Vec<HashMap<String, Value>>>;
}

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager/Devices",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.Device",
    gen_blocking = false
)]
trait NetworkManagerDevice {
    #[dbus_proxy(property)]
    fn interface(&self) -> zbus::Result<String>;

    #[dbus_proxy(property)]
    fn ip4_config(&self) -> zbus::Result<ObjectPath>;

    #[dbus_proxy(property)]
    fn hw_address(&self) -> zbus::Result<String>;
}

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager",
    gen_blocking = false
)]
trait NetworkManager {
    #[dbus_proxy(signal)]
    fn state_changed(&self) -> zbus::Result<()>;

    #[dbus_proxy(name = "GetAllDevices")]
    fn get_all_devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {
    let connection = Connection::system().await?;
    let nm_proxy = NetworkManagerProxy::new(&connection).await?;
    let device_paths = nm_proxy.get_all_devices().await?;

    for device_path in device_paths {
        // convert our object path into a NetworkManagerDeviceProxy
        let nm_device_proxy = NetworkManagerDeviceProxy::builder(&connection)
            .path(&device_path)?
            .build()
            .await?;

        let interface = nm_device_proxy.interface().await?;
        let hw_address = nm_device_proxy.hw_address().await?;

        // convert our object path into a NetworkManagerIP4ConfigProxy
        let ip4_config_path = nm_device_proxy.ip4_config().await?;
        let nm_ip4config = NetworkManagerIP4ConfigProxy::builder(&connection)
            .path(ip4_config_path)?
            .build()
            .await?;

        println!("Network device: {} ({})", interface, hw_address);
        if let Ok(addr_data) = nm_ip4config.address_data().await {
            for addr in addr_data.iter() {
                println!(
                    "\t{}/{}",
                    addr.get("address").unwrap().downcast_ref::<str>().unwrap(),
                    addr.get("prefix").unwrap().downcast_ref::<u32>().unwrap()
                );
            }
        }
    }

    Ok(())
}
```

I did try to [follow the documentation for using a struct as a dict](https://dbus2.github.io/zbus/faq.html#how-to-use-a-struct-as-a-dictionary), but I couldn't get that to work for a `Vec<MyStruct>` (signature: `aa{sv}`). It kept complaining that I needed to `impl TryFrom<OwnedValue> for Vec<MyStruct>`, etc.

Is there a more concise way of implementing this, rather then getting the `ObjectPath`'s and then having to build the proxys from them?

**Comment by acheronfail** [comment] 2023-05-18 05:18
After more experimenting, I can use the `#[dbus_proxy(object = "Device")]` for any method that returns **a single `DeviceProxy`**, but I cannot get it to work with a method that returns a list of those objects, i.e., `Vec<DeviceProxy>`.

**Comment by bilelmoussaoui** [comment] 2023-05-18 10:48
> After more experimenting, I can use the `#[dbus_proxy(object = "Device")]` for any method that returns **a single `DeviceProxy`**, but I cannot get it to work with a method that returns a list of those objects, i.e., `Vec<DeviceProxy>`.


As the person who implemented `object` attribute support, I explicitly didn't implement a list of objects support. That would probably require a different attribute.

**Comment by bilelmoussaoui** [comment] 2023-05-18 10:49
> having to downcast_ref<T>().unwrap() for the HashMap<String, Value> map

You can map the dictionary (`a{sv}`) to a struct by using SerializeDict/DeserializeDict derive macros.

**Comment by bilelmoussaoui** [comment] 2023-05-18 10:50
> After more experimenting, I can use the `#[dbus_proxy(object = "Device")]` for any method that returns **a single `DeviceProxy`**, but I cannot get it to work with a method that returns a list of those objects, i.e., `Vec<DeviceProxy>`.

Actually, this is a duplicate of https://github.com/dbus2/zbus/issues/332 =)

**Comment by acheronfail** [comment] 2023-05-18 11:21
> You can map the dictionary (a{sv}) to a struct by using SerializeDict/DeserializeDict derive macros.

I don't think I can do this actually, since it's not returning just a dictionary, but a list of dictionaries. At least this is my attempt:

```rust
#[derive(Debug, DeserializeDict, SerializeDict, Type)]
#[zvariant(signature = "dict")]
struct AddressData {
    address: String,
    prefix: u32,
}

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager/IP4Config",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.IP4Config",
    gen_blocking = false
)]
trait NetworkManagerIP4Config {
    #[dbus_proxy(property)]
    fn address_data(&self) -> zbus::Result<Vec<Address>>;
}
```

fails compilation with:

```txt
error[E0277]: the trait bound `Vec<zbus::Address>: TryFrom<OwnedValue>` is not satisfied
   --> src/main.rs:16:1
    |
16  | / #[dbus_proxy(
17  | |     default_path = "/org/freedesktop/NetworkManager/IP4Config",
18  | |     default_service = "org.freedesktop.NetworkManager",
19  | |     interface = "org.freedesktop.NetworkManager.IP4Config",
20  | |     gen_blocking = false
21  | | )]
    | |__^ the trait `TryFrom<OwnedValue>` is not implemented for `Vec<zbus::Address>`
    |
    = help: the following other types implement trait `TryFrom<T>`:
              <Vec<T> as TryFrom<OwnedValue>>
              <Vec<T> as TryFrom<zbus::zvariant::Array<'a>>>
              <Vec<T> as TryFrom<zbus::zvariant::Value<'a>>>
note: required by a bound in `zbus::Proxy::<'a>::cached_property`
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.13.1/src/proxy.rs:698:12
    |
698 |         T: TryFrom<OwnedValue>,
    |            ^^^^^^^^^^^^^^^^^^^ required by this bound in `Proxy::<'a>::cached_property`
    = note: this error originates in the attribute macro `dbus_proxy` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by zeenix** [comment] 2023-05-18 11:29
> I don't think I can do this actually, since it's not returning just a dictionary, but a list of dictionaries. At least this is my attempt:

That's the property requirement: type must implement `Value` and/or `OwnedValue`. In fact, just by coincidence[ we even have a test case](https://github.com/dbus2/zbus/blob/main/zbus/tests/e2e.rs#L33) specifically for this type.

**Closed by zeenix** 2023-05-18 11:29 UTC

**Comment by zeenix** [comment] 2023-05-18 11:38
Oh wait, you need an array of dicts, but given that zvariant provides a generic impl of TryFrom<OwnedValue> for Vec<T>`, just adding those derives should fix your issue.

**Comment by acheronfail** [comment] 2023-05-18 12:55
Ahhh that was it!! Thank you! :slightly_smiling_face: 

For anyone reading in the future, this works:

```rust
#[derive(Debug, DeserializeDict, SerializeDict, Value, OwnedValue, Type)]
#[zvariant(signature = "dict")]
struct AddressData {
    address: String,
    prefix: u32,
}

#[dbus_proxy(
    default_path = "/org/freedesktop/NetworkManager/IP4Config",
    default_service = "org.freedesktop.NetworkManager",
    interface = "org.freedesktop.NetworkManager.IP4Config",
    gen_blocking = false
)]
trait NetworkManagerIP4Config {
    #[dbus_proxy(property)]
    fn address_data(&self) -> zbus::Result<Vec<AddressData>>;
}
```

**Comment by zeenix** [comment] 2023-05-19 11:50
> Ahhh that was it!! Thank you! slightly_smiling_face

glad to hear it. :+1: 

> For anyone reading in the future, this works:

Thanks for this. Please do note that our book [does document this requirement](https://dbus2.github.io/zbus/client.html#trait-bounds-for-property-values). If you've ideas on how we can improve the docs on this, do let us know. :pray:
