### ISSUE TITLE
`dbus_interface` failes for methods taking container by reference

### ISSUE THREAD

**Issue by goofacz** [dbus2/zbus#487] opened 2023-10-06 09:27 UTC
Minimal example reproducing the problem:
```rust
use zbus::dbus_proxy;
use zbus::dbus_interface;

struct Foo {}

#[dbus_interface(name = "org.myservice.Foo")]
impl Foo {
    async fn bar(
        &self,
        _params: &[(u32, bool)],
    ) -> zbus::fdo::Result<()> {
        Ok(())
    }
}

#[dbus_proxy(
    interface = "org.myservice.Foo",
    assume_defaults = true
)]
trait Foo {
    async fn bar(
        &self,
        params: &[(u32, bool)],
    ) -> zbus::fdo::Result<()>;
}

fn main() {}
```

Compiler error:
```rust
error[E0277]: the trait bound `&[(u32, bool)]: Deserialize<'_>` is not satisfied
   --> src/main.rs:6:1
    |
6   | #[dbus_interface(name = "org.myservice.Foo")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `&[(u32, bool)]`
    |
    = help: the following other types implement trait `Deserialize<'de>`:
              [T; 0]
              [T; 1]
              [T; 2]
              [T; 3]
              [T; 4]
              [T; 5]
              [T; 6]
              [T; 7]
            and 26 others
    = note: required for `&[(u32, bool)]` to implement `DynamicDeserialize<'_>`
note: required by a bound in `zbus::Message::body`
   --> /home/goofy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/message.rs:395:12
    |
393 |     pub fn body<'d, 'm: 'd, B>(&'m self) -> Result<B>
    |            ---- required by a bound in this associated function
394 |     where
395 |         B: zvariant::DynamicDeserialize<'d>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Message::body`
    = note: this error originates in the attribute macro `dbus_interface` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `xxx` (bin "xxx") due to previous error
```

Methods taking vector by reference to slice is natural way of writing code. Unfortunately such methods fails to compile in D-Bus interfaces created with `dbus_interface`.

`dbus_proxy` is not affected by this problem.

Tested with:
 - zvariant v3.15.0
 - zbus_names v2.6.0
 - zbus v3.14.1
 - rust (recent stable)
 - up-to-date Arch Linux

**Comment by zeenix** [comment] 2023-10-06 14:35
Thanks for reporting this. I don't think we can support this though. As the error says, the type needs to be something we can deserialize to and you can't do that with a slice AFAIK. :thinking: 

Will still look into this though and see if some solution is somehow possible.

**Comment by zeenix** [comment] 2023-11-28 15:02
This is duplicate of #412. The question would be if we can support this (I'd like that) or fix xmlgen to produce working code.

**Closed by zeenix** 2023-11-28 15:02 UTC
