### ISSUE TITLE
rust-analyzer unable to see some types in `zbus::fdo`

### ISSUE THREAD

**Issue by FineFindus** [dbus2/zbus#671] opened 2024-03-07 17:18 UTC
Due to a regression introduced with the new macros in 2189e16a333afe71ddb4c21ab24e49e36a29e53d, rust-analyzer is no longer able to see some of the generated interfaces / infer the types of e.g. `zbus::fdo::ObjectManagerProxy`. It's only rust-analyzer that has this problem, cargo check, clippy, and compiling and running the code work fine. There may be other types that have this problem, though I haven't noticed any. 
I found this with `git bisect` and confirmed it by manually changing the macros back to the old ones, after which rust-analyzer is able to infer the type correctly.

| Before                                                                                                                                    	| After                                                                                                                                                  	|
|-------------------------------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------------------------	|
| ![rust-analyzer correctly infers the type](https://github.com/dbus2/zbus/assets/63370021/ab9328a6-02f3-4779-8616-061e51c4cbd5)            	| ![rust-analyzer is unable to infer the type of ObjectManagerProxy](https://github.com/dbus2/zbus/assets/63370021/4554066e-07e2-42e7-aebf-815d546abc63) 	|
| ![auto-completion of all available fdo types in 3.15](https://github.com/dbus2/zbus/assets/63370021/8e75fe90-a991-448c-981e-40894cc251fe) 	| ![auto-completion of all available fdo types in 4.1.2](https://github.com/dbus2/zbus/assets/63370021/dadfdf14-1576-4cdb-bdef-2e9e1acd2b68)             	|

**Comment by TTWNO** [comment] 2024-04-03 19:58
There are a couple things I'm considering first. Given that the structures/traits/modules do indeed exist, they are just hidden from Rust Analyzer... it makes me think that it's actually a Rust Analyzer problem—even if I did introduce the change that broke it.

First of all, [completion does not work within a macro_rules! invocations](https://github.com/rust-lang/rust-analyzer/issues/12524#issuecomment-1750270911), and also [using cfg_attr and proc-macros together causes completion to stop working](https://github.com/rust-lang/rust-analyzer/issues/15060). These together make me wonder (apologies I haven't had time to diagnose it yet), if we have somehow triggered a similar edge case in that commit—my guess is as good as yours as to the *exact* location of the problem, but I will look into this when I have time and see if this is an issue of incomplete code, or an issue upstream with Rust Analyxer itself.

**Comment by zeenix** [comment] 2024-04-04 13:04
> There are a couple things I'm considering first. Given that the structures/traits/modules do indeed exist, they are just hidden from Rust Analyzer... it makes me think that it's actually a Rust Analyzer problem—even if I did introduce the change that broke it.

That's always possible.

**Comment by zeenix** [comment] 2024-06-13 09:45
> First of all, [completion does not work within a macro_rules! invocations](https://github.com/rust-lang/rust-analyzer/issues/12524#issuecomment-1750270911),

I think that's likely our culprit. I'm right now switching `fdo` mod over to using the new proxy generation feature of `interface` macro and `macro_rules` use is going to be dropped as part of that. While working on that, I noticed that completion starts working perfectly so I'm 100% sure this is the issue.

In any case, the issue is [in R-A really](https://github.com/rust-lang/rust-analyzer/issues/12524#issuecomment-1750270911) so I'm closing this one.

**Comment by zeenix** [comment] 2024-06-13 11:38
> I think that's likely our culprit. I'm right now switching `fdo` mod over to using the new proxy generation feature of `interface` macro and `macro_rules` use is going to be dropped as part of that. While working on that, I noticed that completion starts working perfectly if there is no `macro_rules` involved, so I'm 100% sure this is the issue.

Actually, no. I removed all macro_rules use but completion won't work. However, it works if `interface` generates the proxy, which is super strange since it also uses `proxy` macro. :exploding_head:

**Comment by zeenix** [comment] 2024-09-22 22:36
Closing this in favour of https://github.com/rust-lang/rust-analyzer/issues/18138. It seems they most likely already have a fix (https://github.com/rust-lang/rust-analyzer/pull/18160). :partying_face:

**Closed by zeenix** 2024-09-22 22:36 UTC
