### ISSUE TITLE
New error while recieving DBus messages

### ISSUE THREAD

**Issue by hpux735** [dbus2/zbus#503] opened 2023-11-04 03:30 UTC
Hi,

We've been using ZBus for a while, and I've recently had to rebuild some of our binaries.  I'm not sure what the details exactly are, but we recently had to rebuild our binary, and we have a new error.  I'm not sure what changed, but we're seeing a new error:

`Error: ZBusError(Variant(Message("invalid value: string \"()\", expected at least one field signature between `(` and `)`")))`

This occurs for builds of the binary on our codebase that didn't have an issue before.  I even re-ran a CI pipeline that had worked, and the tests failed.

Do you have any advice for where to start looking for change?

**Comment by zeenix** [comment] 2023-11-04 11:10
I'm very sorry if there had been a regression. What would help me track down the issue if you could:

* Tell me which was the latest version that works so we can narrow down the changes.

* Provide a simple reproducer code. Then I can reproduce locally and hopefully fix the issue.

**Comment by hpux735** [comment] 2023-11-04 19:34
Thanks for responding!  I've been able to get a reproducer that's pretty minimal:

https://gitlab.com/Housedillon/zbus-minimal-reproducer

**Comment by hpux735** [comment] 2023-11-04 21:28
I can't seem to force cargo to load patch versions older than the newest major version specified in the `Cargo.toml`, so I don't know what the newest version that worked prior to 2.3.2 was.  Even if I select `2.2.0`, I still get `2.3.2`.  I do see that the latest in the `3.0.0`+ series works, but there are other issues with compilation that came up in the API change.

**Comment by zeenix** [comment] 2023-11-04 22:09
I'm sorry but version 3.x is the latest supported major version. I'm mostly working alone on this project so I can't possibly support multiple versions. We're in fact in the process of releasing 4.0 soon.

I'd suggest porting your code to 3.x API.

**Comment by hpux735** [comment] 2023-11-04 23:03
Do you have a porting guide?  Many of the errors are inscrutable.   In particular there appear to have been changes to the Message and MessageBuilder types that are weird.  And `zbus::message` is private, which is making accessing some of the types impossible.

**Comment by zeenix** [comment] 2023-11-05 01:21
> Do you have a porting guide? 

I'm sorry but I didn't get the time to write one. There weren't any big changes from 2.x to 3.x really. Mostly it was tighter integration with Tokio when `tokio` feature is enabled.

> Many of the errors are inscrutable. In particular there appear to have been changes to the Message and MessageBuilder types that are weird.  And `zbus::message` is private,

[It's not](https://docs.rs/zbus/latest/zbus/struct.Message.html). You must be doing something very strange. I'll check your reproducer code tomorrow and see if I can find what is going on.

**Comment by zeenix** [comment] 2023-11-05 01:26
Quickly checked your Cargo.toml and I don't see anything wrong there but I do see that you're depending on zvariant and zbus_names directly. The version mismatch can cause issues so I'd strongly suggest using them through [zbus' re-exports](https://docs.rs/zbus/latest/zbus/index.html#reexports).

**Comment by zeenix** [comment] 2023-11-05 13:10
I made a oneliner change to your reproducer:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index a4f3dcc..f7b0f3d 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -10,7 +10,7 @@ log = "0.4.14"
 pretty_env_logger = "0.5.0"
 tokio-stream = "0.1.6"
 tokio = { version = "1.6.0", features = ["full"] }
-zbus = "2.3.2"
+zbus = "3"
 zbus_names = "2.1.0"
 zvariant = "3.2.0"
```

And it builds and runs just fine.

**Comment by zeenix** [comment] 2023-11-05 13:12
Looking at the code, you're not even doing anything other than creating a connection. Not sure, how it was supposed to be reproducer of anything. Creation of connection like that, is tested in our CI on multiple platforms so I don't see how we can break anything in any release.

**Comment by zeenix** [comment] 2023-11-05 13:16
> > Many of the errors are inscrutable. In particular there appear to have been changes to the Message and MessageBuilder types that are weird.  And `zbus::message` is private,
> 
> [It's not](https://docs.rs/zbus/latest/zbus/struct.Message.html). You must be doing something very strange. I'll check your reproducer code tomorrow and see if I can find what is going on.

I just noticed you wrote `message` and not `Message`? Are you by any chance using zbus from git main? That is currently zbus 4, which **will** have breaking changes (mostly in the lower-level though) but I intend to write a short porting guide for that one. For now I'd suggest porting your code to version 3 (from crates.io).

**Comment by hpux735** [comment] 2023-11-05 15:25
Correct, it's lower-case message.  I'm using zbus 3.14.1 and having this particular issue.

regarding the minimal reproducer, correct.  It's doing basically nothing, but that's all it takes to reliably get this result:
```
cargo run                         
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/zbus-minimal-reproducer`
Error: invalid value: string "()", expected at least one field signature between `(` and `)`

Caused by:
    invalid value: string "()", expected at least one field signature between `(` and `)`

Location:
    src/main.rs:10:28
```

**Comment by zeenix** [comment] 2023-11-05 15:44
> Correct, it's lower-case message. I'm using zbus 3.14.1 and having this particular issue.

I don't quite understand then what you said about `message`. The `message` mod was created in 21c17eae9cc060fe8a9db6a6c52afa4b5623db0b, which was committer after 3.14.1 and has not been included in any release. Also it's never been private.

> regarding the minimal reproducer, correct. It's doing basically nothing, but that's all it takes to reliably get this result:

As I wrote, I'm unable to reproduce on my machine. Can you try clearing all caches on you machine?

**Comment by zeenix** [comment] 2023-11-05 15:49
> > regarding the minimal reproducer, correct. It's doing basically nothing, but that's all it takes to reliably get this result:
> 
> As I wrote, I'm unable to reproduce on my machine. Can you try clearing all caches on you machine?

Oh, if i run your reproducer as is, it does indeed give me the same output as you pasted above. :thinking: I'll check what's going on.

**Comment by zeenix** [comment] 2023-11-05 15:51
> > > regarding the minimal reproducer, correct. It's doing basically nothing, but that's all it takes to reliably get this result:
> > 
> > 
> > As I wrote, I'm unable to reproduce on my machine. Can you try clearing all caches on you machine?
> 
> Oh, if i run your reproducer as is, it does indeed give me the same output as you pasted above. 🤔 I'll check what's going on.

Actually, no. The issue is easily resolved with switching seemlessly to the latest supported version and I don't  have time to debug unsupported old versions.

**Closed** 2023-11-05 15:51 UTC
